/// <reference types="vite/client" />

/**
 * Global Type Definitions
 *
 * Note: Most asset types (images, css modules) are already covered by 'vite/client'.
 * Specific CSS module types are generated by 'vite-plugin-sass-dts' in src/__generated__.
 */

interface Window {
  // Add custom window properties here
  // Telegram?: any;
}

// Custom SVG declaration for projects that use SVGR
declare module "*.svg?react" {
  import { FunctionComponent, SVGProps } from 'react';
  const ReactComponent: FunctionComponent<SVGProps<SVGSVGElement> & { title?: string }>;
  export default ReactComponent;
}
